version: '3.9'
services:
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: "db"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "password"
      ports:
        - "5432:5432"